### ISSUE TITLE
Poor Visibility for some icons 

### ISSUE THREAD

**Issue by ErikFunkhouser** [Nevcairiel/GatherMate2#17]
For the World Map. Example: Writhebark in The Azure Span. Symbol color matches mountains almost exactly, and at any scale is difficult to discern. Suggest adding a single green dot/circle for every icon to call attention to the node, with the image underneath to clarify which item.

**Comment by Nevcairiel** [comment]
Modern zones have so many nodes all over the zone that I find any display on the world map or minimap pretty pointless. Especially on the world map, nodes will pretty much always overlap or sit so close to each other that its not really worth looking at them, but rather only collect their location so it can be used eg. for Routes.

I do not have any plans to make that display even more busy by introducing backdrops or outlines.

**Comment by ErikFunkhouser** [comment]
My only counterpoint is: Writhebark is 100x the price on the AH as Hochenblum, which to me makes it worthwhile to filter Hochenbloom entirely off the map and only focus on Writhebark, which even with the other herbs clears up the map significantly. Instead of it being default, just having an option to toggle something that makes visibility easier would be valuable in that use-case. Alternatively, an experiment could be giving herbs a similar hue that doesn't fight with the map background across various terrain types (such as purple) and allow the silhouette of the herb to make it obvious to users which herb it is, not sure if this is effective, it would have to be tested, but once again, this could be a toggle on/off effect. 

Anyways, thanks for the quick response, definitely not a do or die kind of issue, so I appreciate the thoughts on it and this should be my last transmission :)
