### ISSUE TITLE
Classic Era: Attempt to register unknown event "CURSOR_UPDATE"

### ISSUE THREAD

**Issue by kriminy** [Nevcairiel/GatherMate2#19]
With the new patch for Classic Era (TOC version 1.14.4), the client has been updated to be based on the Dragonflight client. The API event CURSOR_UPDATE is now deprecated as a result, causing the following LUA error:

AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:132: in function `RegisterEvent'
[string "@GatherMate2/Collector.lua"]:81: in function `RegisterGatherEvents'
[string "@GatherMate2/Collector.lua"]:67: in function <GatherMate2/Collector.lua:66>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"

**Comment by Nevcairiel** [comment]
I've published an update earlier today that should address this.
