### ISSUE TITLE
Cataclysm update?

### ISSUE THREAD

**Issue by ForgeGit** [Nevcairiel/GatherMate2#25]
Title.

**Comment by ynazar1** [comment]
With Archaeology :)

**Comment by ynazar1** [comment]
In addition to putting back all the ARH configs back into the classic gathermate. Don't miss the bug in Display.lua:

```
function Display:ChangedVars(event,cvar,value)
	 WRONG --> if cvar == "ROTATE_MINIMAP" then
         CORRECT --> if cvar == "rotateMinimap" then
		rotateMinimap = value == "1"
	end
	forceNextUpdate = true
end
```

**Comment by ynazar1** [comment]
Or grab my zip cause i did the Archaeology work already: [https://github.com/ynazar1/Arh/issues/12 from ](https://github.com/ynazar1/Arh/issues/12#issuecomment-2089427000)

**Comment by towicode** [comment]
@Nevcairiel 

I grabbed data from retail and adjusted it to work in cata classic. figured I'd share here incase you wanna use it. I have it displayed as herbalism data atm but the zones and coords seem correct so far.

https://pastebin.com/raw/BqAeSfZ9

**Comment by Nevcairiel** [comment]
Archaelogy collection support is available now.

**Comment by ynazar1** [comment]
Quick test confirming compatibility with Arh and functionality working fine. 👍

**Comment by blasfury4** [comment]
> @Nevcairiel
> 
> I grabbed data from retail and adjusted it to work in cata classic. figured I'd share here incase you wanna use it. I have it displayed as herbalism data atm but the zones and coords seem correct so far.
> 
> https://pastebin.com/raw/BqAeSfZ9

how to import this?
