### ISSUE TITLE
Cataclysm Data

### ISSUE THREAD

**Issue by Jordan466** [Nevcairiel/GatherMate2#26]
Hello. just wanted to know how we get the latest data for cataclysm. Importing the cata database currently results in nodes from before the shattering

**Comment by Nevcairiel** [comment]
I don't provide data for Classic, it sounds like whatever data addon has taken up that task will need an update.

**Comment by Jordan466** [comment]
Sorry. You're right. I hadn't noticed you weren't the maintainer of the [data](https://www.curseforge.com/wow/addons/gathermate2-data-wowhead-classic)
