### ISSUE TITLE
GatherMate2 Classic - Outdated/Non-functioning links

### ISSUE THREAD

**Issue by Voilak** [Nevcairiel/GatherMate2#5]
Hello,

I want to inform you that throughout the whole internet, there is not a single version of the GatherMate2 addon that works. Curseforge, Twitch app, legacy-wow, you name any site you want. Only version available is {GatherMate2-1.45.5} and it's for patch 8.2.5 and when you put it in classic wow it says it's outdated and it doesn't even function regardless of loading it. Did fresh installs over 20 times with every possible resource I could find. If you have a functioning link for classic wow, do share/update it.

Thank you.

**Comment by cloonix** [comment]
Looks like they abandoned it.

**Comment by Nevcairiel** [comment]
The classic version on CurseForge works just fine.

**Comment by Nevcairiel** [comment]
Actually due to conflicting localizations, GatherMate2 for Classic is now available separately here:
https://www.wowace.com/projects/gathermate2-classic
