### ISSUE TITLE
attempt to index global 'c_minimap' (a nil value)

### ISSUE THREAD

**Issue by swissb00m** [Nevcairiel/GatherMate2#6]
Hello

Since this morning i see this with counting up (few thousands times since login):

Message: Interface\addons\gathermate2\display.lua:682: attempt to index global 'c_minimap' (a nil value)
stack: Interface\addons\gathermate2\display.lua:682: attempt to index global 'c_minimap' (a nil value)
[C]: ?
Interface\addons\gathermate2\display.lua:682: in function 'UpdateMiniMap'
Interface\addons\gathermate2\display.lua:232: in function <Interface\addons\gathermate2\display.lua:229>

If i disable the option "Show Minimap Icons" (under GatherMate2 -> Minimap) the lua error is not showing up again.

**Comment by Nevcairiel** [comment]
You are using the retail version on classic. Update to the proper classic version.
