### ISSUE TITLE
GetNumTrickingTypes nil value

### ISSUE THREAD

**Issue by stupedama** [Nevcairiel/GatherMate2#7]
After updating GatherMate2 i get this error. I tried the beta and the stable version. Currently I'm on 1.46.3

Date: 2020-12-01 11:16:40
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\GatherMate2\Display.lua line 316:
   attempt to call global 'GetNumTrackingTypes' (a nil value)
Debug:
   (tail call): ?
   GatherMate2\Display.lua:316: ?()
   ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AngryAssignments, vv1.13.2c
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AuctionFaster, v1.13.9
  BagBrother, v
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.7
  ClassicCastbars, vv1.3.14
  ClassicCastbarsOptions, v
  ClassicGoldTracker, v
  ClassicLootAssistant, v
  DBMCore, v1.13.61
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  EPGPClassic, vv1.5.5
  GatherMate2, v1.46.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  ItemSurveyClassic, v1.73
  LoggerHeadLiteClassic, v1.0.5
  NovaWorldBuffs, v1.84
  Questie, v6.2.2
  RCLootCouncilClassic, v0.11.2
  ShowMeMyHeal, v0.6.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TankWarningsClassic, v1.1.9(BETA)
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  VendorPrice, v1.3.7
  vUI, v1.0096
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.9.2
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=79f)

**Comment by Nevcairiel** [comment]
You are using the retail version on classic, swap to the correct one at https://www.curseforge.com/wow/addons/gathermate2-classic
